@startuml
    class Estacion {
        - nombre: String
        - numEstacion: int
        + Estacion()
        + Estacion(int num)
        + Estacion(String nom, int numEst)
        + getNombre(): String
        + setNombre(String nombre): void
        + getNumEstacion(): int
        + setNumEstacion(int numEstacion): void
        + equals(Object e): boolean
        + toString(): String
    }

@enduml
